[tool.poetry]
name = "books-base"
version = "0.1.0"
description = ""
authors = ["sonic_72_kon <kko160305@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
aiogram = "^3.4.1"
environs = "^10.3.0"
redis = "^5.0.2"
betterlogging = "^1.0.0"
asyncpg = "^0.29.0"
greenlet = "^3.0.3"
alembic = "^1.13.1"
sqlalchemy = {extras = ["asyncio"], version = "^2.0.28"}


[tool.poetry.group.dev.dependencies]
black = "^24.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
